# 第3章：NumPy运算

NumPy提供了强大的运算功能，使得对数组的数学和统计操作变得高效而简单。本章将详细介绍NumPy的运算能力，帮助你掌握如何使用它进行数值计算。

## 3.1 基本数学运算

NumPy支持对数组进行**逐元素运算**，这是一种向量化操作，可以避免使用循环，提高计算效率。我们将介绍逐元素运算、标量与数组的运算，以及通用函数（ufunc）。

### 3.1.1 逐元素运算

NumPy中的基本运算符（如 `+`、`-`、`*`、`/`）会对数组的每个元素执行相同操作。

**示例：**

In [2]:
import numpy as np

# 创建两个一维数组
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# 逐元素加法
print("a + b:", a + b)  # 输出: [ 6  8 10 12]

# 逐元素减法
print("a - b:", a - b)  # 输出: [-4 -4 -4 -4]

# 逐元素乘法
print("a * b:", a * b)  # 输出: [ 5 12 21 32]

# 逐元素除法
print("a / b:", a / b)  # 输出: [0.2        0.33333333 0.42857143 0.5       ]

a + b: [ 6  8 10 12]
a - b: [-4 -4 -4 -4]
a * b: [ 5 12 21 32]
a / b: [0.2        0.33333333 0.42857143 0.5       ]


**讲解：**

- 逐元素运算要求两个数组的形状相同（或者符合广播规则，详见3.3节）。
- 这种操作比Python循环更快，因为NumPy在底层使用了优化的C代码。

### 3.1.2 标量与数组的运算

标量（单个数字）可以与数组运算，标量会自动扩展到与数组相同的形状。

**示例：**

In [2]:
# 创建一个数组
a = np.array([1, 2, 3, 4])

# 标量加法
print("a + 10:", a + 10)  # 输出: [11 12 13 14]

# 标量乘法
print("a * 2:", a * 2)    # 输出: [2 4 6 8]

# 标量除法
print("a / 2:", a / 2)    # 输出: [0.5 1.  1.5 2. ]

a + 10: [11 12 13 14]
a * 2: [2 4 6 8]
a / 2: [0.5 1.  1.5 2. ]


**讲解：**

- 标量运算利用了广播机制（详见3.3节），无需手动扩展标量。
- 这使得代码更简洁，计算更高效。

### 3.1.3 通用函数（ufunc）

NumPy提供了**通用函数（ufunc）**，这些函数对数组的每个元素应用数学操作，例如三角函数、指数、对数等。

**常用ufunc：**

- `np.sin()`：正弦函数
- `np.cos()`：余弦函数
- `np.exp()`：指数函数
- `np.log()`：自然对数
- `np.sqrt()`：平方根

**示例：**

In [3]:
# 创建一个数组
a = np.array([0, np.pi/2, np.pi])

# 计算正弦
print("sin(a):", np.sin(a))  # 输出: [0.0000000e+00 1.0000000e+00 1.2246468e-16]

# 计算指数
print("exp(a):", np.exp(a))  # 输出: [ 1.          4.81047738 23.14069263]

# 计算平方根
print("sqrt(a):", np.sqrt(a))  # 输出: [0.         1.25331414 1.77245385]

sin(a): [0.0000000e+00 1.0000000e+00 1.2246468e-16]
exp(a): [ 1.          4.81047738 23.14069263]
sqrt(a): [0.         1.25331414 1.77245385]


**讲解：**

- ufunc是NumPy的核心功能，专门为数组运算优化。
- 这些函数比Python内置数学函数（如 `math.sin`）更快，适合处理大量数据。

---

## 3.2 统计函数

NumPy提供了丰富的统计函数，用于计算数组的统计量，如求和、平均值、标准差等。可以对整个数组或沿指定轴计算。

### 3.2.1 基本统计函数

**常用统计函数：**

- `np.sum()`：求和
- `np.mean()`：平均值
- `np.std()`：标准差
- `np.var()`：方差
- `np.min()`：最小值
- `np.max()`：最大值

**示例：**

In [5]:
# 创建一个二维数组
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 对整个数组求和
print("所有元素之和:", np.sum(arr))  # 输出: 45

# 按列求和（沿axis=0）
print("每列之和:", np.sum(arr, axis=0))  # 输出: [12 15 18]

# 按行求和（沿axis=1）
print("每行之和:", np.sum(arr, axis=1))  # 输出: [ 6 15 24]

# 计算平均值
print("所有元素平均值:", np.mean(arr))  # 输出: 5.0

# 计算标准差
print("标准差:", np.std(arr))  # 输出: 2.581988897471611

所有元素之和: 45
每列之和: [12 15 18]
每行之和: [ 6 15 24]
所有元素平均值: 5.0
标准差: 2.581988897471611


**讲解：**

- 参数 `axis` 指定运算方向：`0` 表示按列，`1` 表示按行。
- 这些函数返回标量（对整个数组）或数组（沿轴计算）。

### 3.2.2 最大值和最小值及其索引

**相关函数：**

- `np.min()`：最小值
- `np.max()`：最大值
- `np.argmin()`：最小值索引
- `np.argmax()`：最大值索引

**示例：**

In [3]:
# 创建一个一维数组
arr = np.array([10, 20, 30, 25, 15])

# 最小值和最大值
print("最小值:", np.min(arr))  # 输出: 10
print("最大值:", np.max(arr))  # 输出: 30

# 最小值和最大值的索引
print("最小值索引:", np.argmin(arr))  # 输出: 0
print("最大值索引:", np.argmax(arr))  # 输出: 2

最小值: 10
最大值: 30
最小值索引: 0
最大值索引: 2


**讲解：**

- `argmin` 和 `argmax` 返回展平后的索引。
- 对于多维数组，可用 `np.unravel_index()` 转换为多维坐标。

---

## 3.3 广播机制

**广播（Broadcasting）** 是NumPy中一个强大功能，允许不同形状的数组进行运算。它通过自动扩展数组的维度来实现。

### 3.3.1 广播的规则

1. 如果两个数组维度不同，低维数组会在前面补1，直到维度相同。
2. 每个维度上，形状相同或其中一个为1，则兼容。
3. 否则，无法广播。

**示例：**

- `(3, 2)` 和 `(2,)` 可以广播（第二个维度兼容）。
- `(3, 2)` 和 `(3, 1)` 可以广播（第二个维度为1）。
- `(3, 2)` 和 `(2, 3)` 无法广播。

### 3.3.2 广播的应用

**示例1：标量与数组广播**

In [5]:
# 创建二维数组
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# 标量广播
result = arr + 10
print(result)
# 输出:
# [[11 12 13]
#  [14 15 16]]

[[11 12 13]
 [14 15 16]]


**示例2：一维与二维数组广播**

In [4]:
# 创建二维和一维数组
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr1d = np.array([10, 20, 30])

# 一维数组广播到每行
result = arr2d + arr1d
print(result)
# 输出:
# [[11 22 33]
#  [14 25 36]]

[[11 22 33]
 [14 25 36]]


**示例3：列向量与行向量广播**

In [8]:
# 创建列向量和行向量
col_vec = np.array([[1], [2], [3]])  # 形状 (3, 1)
row_vec = np.array([10, 20, 30])     # 形状 (3,)
print(col_vec)
print(row_vec)
# 广播生成矩阵
result = col_vec + row_vec
print(result)
# 输出:
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]

[[1]
 [2]
 [3]]
[10 20 30]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


**讲解：**

- 广播简化了代码，避免了手动扩展数组。
- 使用前需检查形状兼容性，以防错误。

---

## 3.4 线性代数操作

NumPy支持线性代数运算，适用于矩阵计算。以下为常用操作：

### 3.4.1 矩阵乘法

**函数：**

- `np.dot()`：点积
- `np.matmul()`：矩阵乘法（推荐）

**示例：**

In [11]:
# 创建两个矩阵
a = np.array([[1, 2],
               [3, 4]])
b = np.array([[5, 6],
               [7, 8]])

result1=np.dot(a,b)
print(result1)
result = np.matmul(a, b)
print(result)
# 输出:
# [[19 22]
#  [43 50]]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### 3.4.2 逆矩阵

**函数：**

- `np.linalg.inv()`：计算逆矩阵

**示例：**

In [5]:
# 创建可逆矩阵
a = np.array([[1, 2],
              [3, 4]])

# 计算逆矩阵
inv_a = np.linalg.inv(a)
print(inv_a)
# 输出:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

[[-2.   1. ]
 [ 1.5 -0.5]]


对于非方阵或不可逆矩阵，可以使用伪逆（Moore-Penrose逆），通过`np.linalg.pinv()`计算。

In [6]:
# 创建一个非方阵
b = np.array([[1, 2, 3], [4, 5, 6]])

# 求伪逆
pinv_b = np.linalg.pinv(b)
print("伪逆:\n", pinv_b)

伪逆:
 [[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]


### 3.4.3 特征值和特征向量

**函数：**

- `np.linalg.eig()`：计算特征值和特征向量

**示例：**

In [7]:
# 创建矩阵
a = np.array([[1, 2],
              [2, 1]])

# 计算特征值和特征向量
eigvals, eigvecs = np.linalg.eig(a)
print("特征值:", eigvals)
print("特征向量:\n", eigvecs)
# 输出:
# 特征值: [ 3. -1.]
# 特征向量:
# [[ 0.70710678 -0.70710678]
#  [ 0.70710678  0.70710678]]

特征值: [ 3. -1.]
特征向量:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


### 奇异值分解（SVD）

奇异值分解（SVD）是一种通用的矩阵分解方法，适用于任意矩阵。使用`np.linalg.svd()`计算。

In [8]:
# 创建一个矩阵
a = np.array([[1, 2], [3, 4], [5, 6]])

# 进行SVD分解
U, S, V = np.linalg.svd(a)
print("U:\n", U)
print("S:", S)
print("V:\n", V)

U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S: [9.52551809 0.51430058]
V:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
